// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_rpc.proto

package com.example.rpc;

public final class LoginProto {
  private LoginProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AuthBaseRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.entities.AuthBaseRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string refId = 1;</code>
     * @return The refId.
     */
    java.lang.String getRefId();
    /**
     * <code>string refId = 1;</code>
     * @return The bytes for refId.
     */
    com.google.protobuf.ByteString
        getRefIdBytes();

    /**
     * <code>string stringValue = 2;</code>
     * @return The stringValue.
     */
    java.lang.String getStringValue();
    /**
     * <code>string stringValue = 2;</code>
     * @return The bytes for stringValue.
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <code>repeated string stringValues = 3;</code>
     * @return A list containing the stringValues.
     */
    java.util.List<java.lang.String>
        getStringValuesList();
    /**
     * <code>repeated string stringValues = 3;</code>
     * @return The count of stringValues.
     */
    int getStringValuesCount();
    /**
     * <code>repeated string stringValues = 3;</code>
     * @param index The index of the element to return.
     * @return The stringValues at the given index.
     */
    java.lang.String getStringValues(int index);
    /**
     * <code>repeated string stringValues = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the stringValues at the given index.
     */
    com.google.protobuf.ByteString
        getStringValuesBytes(int index);

    /**
     * <code>int32 intValue = 4;</code>
     * @return The intValue.
     */
    int getIntValue();

    /**
     * <code>int64 longValue = 5;</code>
     * @return The longValue.
     */
    long getLongValue();

    /**
     * <code>bool boolValue = 6;</code>
     * @return The boolValue.
     */
    boolean getBoolValue();

    /**
     * <code>bool doubleValue = 7;</code>
     * @return The doubleValue.
     */
    boolean getDoubleValue();
  }
  /**
   * Protobuf type {@code com.example.entities.AuthBaseRequest}
   */
  public static final class AuthBaseRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.entities.AuthBaseRequest)
      AuthBaseRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthBaseRequest.newBuilder() to construct.
    private AuthBaseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthBaseRequest() {
      refId_ = "";
      stringValue_ = "";
      stringValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AuthBaseRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthBaseRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              refId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              stringValue_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                stringValues_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              stringValues_.add(s);
              break;
            }
            case 32: {

              intValue_ = input.readInt32();
              break;
            }
            case 40: {

              longValue_ = input.readInt64();
              break;
            }
            case 48: {

              boolValue_ = input.readBool();
              break;
            }
            case 56: {

              doubleValue_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          stringValues_ = stringValues_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.rpc.LoginProto.internal_static_com_example_entities_AuthBaseRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.rpc.LoginProto.internal_static_com_example_entities_AuthBaseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.rpc.LoginProto.AuthBaseRequest.class, com.example.rpc.LoginProto.AuthBaseRequest.Builder.class);
    }

    public static final int REFID_FIELD_NUMBER = 1;
    private volatile java.lang.Object refId_;
    /**
     * <code>string refId = 1;</code>
     * @return The refId.
     */
    @java.lang.Override
    public java.lang.String getRefId() {
      java.lang.Object ref = refId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refId_ = s;
        return s;
      }
    }
    /**
     * <code>string refId = 1;</code>
     * @return The bytes for refId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRefIdBytes() {
      java.lang.Object ref = refId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRINGVALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object stringValue_;
    /**
     * <code>string stringValue = 2;</code>
     * @return The stringValue.
     */
    @java.lang.Override
    public java.lang.String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringValue_ = s;
        return s;
      }
    }
    /**
     * <code>string stringValue = 2;</code>
     * @return The bytes for stringValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRINGVALUES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList stringValues_;
    /**
     * <code>repeated string stringValues = 3;</code>
     * @return A list containing the stringValues.
     */
    public com.google.protobuf.ProtocolStringList
        getStringValuesList() {
      return stringValues_;
    }
    /**
     * <code>repeated string stringValues = 3;</code>
     * @return The count of stringValues.
     */
    public int getStringValuesCount() {
      return stringValues_.size();
    }
    /**
     * <code>repeated string stringValues = 3;</code>
     * @param index The index of the element to return.
     * @return The stringValues at the given index.
     */
    public java.lang.String getStringValues(int index) {
      return stringValues_.get(index);
    }
    /**
     * <code>repeated string stringValues = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the stringValues at the given index.
     */
    public com.google.protobuf.ByteString
        getStringValuesBytes(int index) {
      return stringValues_.getByteString(index);
    }

    public static final int INTVALUE_FIELD_NUMBER = 4;
    private int intValue_;
    /**
     * <code>int32 intValue = 4;</code>
     * @return The intValue.
     */
    @java.lang.Override
    public int getIntValue() {
      return intValue_;
    }

    public static final int LONGVALUE_FIELD_NUMBER = 5;
    private long longValue_;
    /**
     * <code>int64 longValue = 5;</code>
     * @return The longValue.
     */
    @java.lang.Override
    public long getLongValue() {
      return longValue_;
    }

    public static final int BOOLVALUE_FIELD_NUMBER = 6;
    private boolean boolValue_;
    /**
     * <code>bool boolValue = 6;</code>
     * @return The boolValue.
     */
    @java.lang.Override
    public boolean getBoolValue() {
      return boolValue_;
    }

    public static final int DOUBLEVALUE_FIELD_NUMBER = 7;
    private boolean doubleValue_;
    /**
     * <code>bool doubleValue = 7;</code>
     * @return The doubleValue.
     */
    @java.lang.Override
    public boolean getDoubleValue() {
      return doubleValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRefIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, refId_);
      }
      if (!getStringValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stringValue_);
      }
      for (int i = 0; i < stringValues_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, stringValues_.getRaw(i));
      }
      if (intValue_ != 0) {
        output.writeInt32(4, intValue_);
      }
      if (longValue_ != 0L) {
        output.writeInt64(5, longValue_);
      }
      if (boolValue_ != false) {
        output.writeBool(6, boolValue_);
      }
      if (doubleValue_ != false) {
        output.writeBool(7, doubleValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRefIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, refId_);
      }
      if (!getStringValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stringValue_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stringValues_.size(); i++) {
          dataSize += computeStringSizeNoTag(stringValues_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getStringValuesList().size();
      }
      if (intValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, intValue_);
      }
      if (longValue_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, longValue_);
      }
      if (boolValue_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, boolValue_);
      }
      if (doubleValue_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, doubleValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.rpc.LoginProto.AuthBaseRequest)) {
        return super.equals(obj);
      }
      com.example.rpc.LoginProto.AuthBaseRequest other = (com.example.rpc.LoginProto.AuthBaseRequest) obj;

      if (!getRefId()
          .equals(other.getRefId())) return false;
      if (!getStringValue()
          .equals(other.getStringValue())) return false;
      if (!getStringValuesList()
          .equals(other.getStringValuesList())) return false;
      if (getIntValue()
          != other.getIntValue()) return false;
      if (getLongValue()
          != other.getLongValue()) return false;
      if (getBoolValue()
          != other.getBoolValue()) return false;
      if (getDoubleValue()
          != other.getDoubleValue()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REFID_FIELD_NUMBER;
      hash = (53 * hash) + getRefId().hashCode();
      hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getStringValue().hashCode();
      if (getStringValuesCount() > 0) {
        hash = (37 * hash) + STRINGVALUES_FIELD_NUMBER;
        hash = (53 * hash) + getStringValuesList().hashCode();
      }
      hash = (37 * hash) + INTVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getIntValue();
      hash = (37 * hash) + LONGVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongValue());
      hash = (37 * hash) + BOOLVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBoolValue());
      hash = (37 * hash) + DOUBLEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDoubleValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.rpc.LoginProto.AuthBaseRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rpc.LoginProto.AuthBaseRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rpc.LoginProto.AuthBaseRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rpc.LoginProto.AuthBaseRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rpc.LoginProto.AuthBaseRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rpc.LoginProto.AuthBaseRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rpc.LoginProto.AuthBaseRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.rpc.LoginProto.AuthBaseRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.rpc.LoginProto.AuthBaseRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.rpc.LoginProto.AuthBaseRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.rpc.LoginProto.AuthBaseRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.rpc.LoginProto.AuthBaseRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.rpc.LoginProto.AuthBaseRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.entities.AuthBaseRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.entities.AuthBaseRequest)
        com.example.rpc.LoginProto.AuthBaseRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.rpc.LoginProto.internal_static_com_example_entities_AuthBaseRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.rpc.LoginProto.internal_static_com_example_entities_AuthBaseRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.rpc.LoginProto.AuthBaseRequest.class, com.example.rpc.LoginProto.AuthBaseRequest.Builder.class);
      }

      // Construct using com.example.rpc.LoginProto.AuthBaseRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        refId_ = "";

        stringValue_ = "";

        stringValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        intValue_ = 0;

        longValue_ = 0L;

        boolValue_ = false;

        doubleValue_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.rpc.LoginProto.internal_static_com_example_entities_AuthBaseRequest_descriptor;
      }

      @java.lang.Override
      public com.example.rpc.LoginProto.AuthBaseRequest getDefaultInstanceForType() {
        return com.example.rpc.LoginProto.AuthBaseRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.rpc.LoginProto.AuthBaseRequest build() {
        com.example.rpc.LoginProto.AuthBaseRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.rpc.LoginProto.AuthBaseRequest buildPartial() {
        com.example.rpc.LoginProto.AuthBaseRequest result = new com.example.rpc.LoginProto.AuthBaseRequest(this);
        int from_bitField0_ = bitField0_;
        result.refId_ = refId_;
        result.stringValue_ = stringValue_;
        if (((bitField0_ & 0x00000001) != 0)) {
          stringValues_ = stringValues_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.stringValues_ = stringValues_;
        result.intValue_ = intValue_;
        result.longValue_ = longValue_;
        result.boolValue_ = boolValue_;
        result.doubleValue_ = doubleValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.rpc.LoginProto.AuthBaseRequest) {
          return mergeFrom((com.example.rpc.LoginProto.AuthBaseRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.rpc.LoginProto.AuthBaseRequest other) {
        if (other == com.example.rpc.LoginProto.AuthBaseRequest.getDefaultInstance()) return this;
        if (!other.getRefId().isEmpty()) {
          refId_ = other.refId_;
          onChanged();
        }
        if (!other.getStringValue().isEmpty()) {
          stringValue_ = other.stringValue_;
          onChanged();
        }
        if (!other.stringValues_.isEmpty()) {
          if (stringValues_.isEmpty()) {
            stringValues_ = other.stringValues_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStringValuesIsMutable();
            stringValues_.addAll(other.stringValues_);
          }
          onChanged();
        }
        if (other.getIntValue() != 0) {
          setIntValue(other.getIntValue());
        }
        if (other.getLongValue() != 0L) {
          setLongValue(other.getLongValue());
        }
        if (other.getBoolValue() != false) {
          setBoolValue(other.getBoolValue());
        }
        if (other.getDoubleValue() != false) {
          setDoubleValue(other.getDoubleValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.rpc.LoginProto.AuthBaseRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.rpc.LoginProto.AuthBaseRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object refId_ = "";
      /**
       * <code>string refId = 1;</code>
       * @return The refId.
       */
      public java.lang.String getRefId() {
        java.lang.Object ref = refId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          refId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string refId = 1;</code>
       * @return The bytes for refId.
       */
      public com.google.protobuf.ByteString
          getRefIdBytes() {
        java.lang.Object ref = refId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          refId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string refId = 1;</code>
       * @param value The refId to set.
       * @return This builder for chaining.
       */
      public Builder setRefId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        refId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string refId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRefId() {
        
        refId_ = getDefaultInstance().getRefId();
        onChanged();
        return this;
      }
      /**
       * <code>string refId = 1;</code>
       * @param value The bytes for refId to set.
       * @return This builder for chaining.
       */
      public Builder setRefIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        refId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stringValue_ = "";
      /**
       * <code>string stringValue = 2;</code>
       * @return The stringValue.
       */
      public java.lang.String getStringValue() {
        java.lang.Object ref = stringValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stringValue = 2;</code>
       * @return The bytes for stringValue.
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = stringValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stringValue = 2;</code>
       * @param value The stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stringValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stringValue = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringValue() {
        
        stringValue_ = getDefaultInstance().getStringValue();
        onChanged();
        return this;
      }
      /**
       * <code>string stringValue = 2;</code>
       * @param value The bytes for stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stringValue_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList stringValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStringValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          stringValues_ = new com.google.protobuf.LazyStringArrayList(stringValues_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string stringValues = 3;</code>
       * @return A list containing the stringValues.
       */
      public com.google.protobuf.ProtocolStringList
          getStringValuesList() {
        return stringValues_.getUnmodifiableView();
      }
      /**
       * <code>repeated string stringValues = 3;</code>
       * @return The count of stringValues.
       */
      public int getStringValuesCount() {
        return stringValues_.size();
      }
      /**
       * <code>repeated string stringValues = 3;</code>
       * @param index The index of the element to return.
       * @return The stringValues at the given index.
       */
      public java.lang.String getStringValues(int index) {
        return stringValues_.get(index);
      }
      /**
       * <code>repeated string stringValues = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the stringValues at the given index.
       */
      public com.google.protobuf.ByteString
          getStringValuesBytes(int index) {
        return stringValues_.getByteString(index);
      }
      /**
       * <code>repeated string stringValues = 3;</code>
       * @param index The index to set the value at.
       * @param value The stringValues to set.
       * @return This builder for chaining.
       */
      public Builder setStringValues(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringValuesIsMutable();
        stringValues_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stringValues = 3;</code>
       * @param value The stringValues to add.
       * @return This builder for chaining.
       */
      public Builder addStringValues(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringValuesIsMutable();
        stringValues_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stringValues = 3;</code>
       * @param values The stringValues to add.
       * @return This builder for chaining.
       */
      public Builder addAllStringValues(
          java.lang.Iterable<java.lang.String> values) {
        ensureStringValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stringValues_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stringValues = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringValues() {
        stringValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stringValues = 3;</code>
       * @param value The bytes of the stringValues to add.
       * @return This builder for chaining.
       */
      public Builder addStringValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureStringValuesIsMutable();
        stringValues_.add(value);
        onChanged();
        return this;
      }

      private int intValue_ ;
      /**
       * <code>int32 intValue = 4;</code>
       * @return The intValue.
       */
      @java.lang.Override
      public int getIntValue() {
        return intValue_;
      }
      /**
       * <code>int32 intValue = 4;</code>
       * @param value The intValue to set.
       * @return This builder for chaining.
       */
      public Builder setIntValue(int value) {
        
        intValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intValue = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntValue() {
        
        intValue_ = 0;
        onChanged();
        return this;
      }

      private long longValue_ ;
      /**
       * <code>int64 longValue = 5;</code>
       * @return The longValue.
       */
      @java.lang.Override
      public long getLongValue() {
        return longValue_;
      }
      /**
       * <code>int64 longValue = 5;</code>
       * @param value The longValue to set.
       * @return This builder for chaining.
       */
      public Builder setLongValue(long value) {
        
        longValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 longValue = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongValue() {
        
        longValue_ = 0L;
        onChanged();
        return this;
      }

      private boolean boolValue_ ;
      /**
       * <code>bool boolValue = 6;</code>
       * @return The boolValue.
       */
      @java.lang.Override
      public boolean getBoolValue() {
        return boolValue_;
      }
      /**
       * <code>bool boolValue = 6;</code>
       * @param value The boolValue to set.
       * @return This builder for chaining.
       */
      public Builder setBoolValue(boolean value) {
        
        boolValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool boolValue = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolValue() {
        
        boolValue_ = false;
        onChanged();
        return this;
      }

      private boolean doubleValue_ ;
      /**
       * <code>bool doubleValue = 7;</code>
       * @return The doubleValue.
       */
      @java.lang.Override
      public boolean getDoubleValue() {
        return doubleValue_;
      }
      /**
       * <code>bool doubleValue = 7;</code>
       * @param value The doubleValue to set.
       * @return This builder for chaining.
       */
      public Builder setDoubleValue(boolean value) {
        
        doubleValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool doubleValue = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoubleValue() {
        
        doubleValue_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.entities.AuthBaseRequest)
    }

    // @@protoc_insertion_point(class_scope:com.example.entities.AuthBaseRequest)
    private static final com.example.rpc.LoginProto.AuthBaseRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.rpc.LoginProto.AuthBaseRequest();
    }

    public static com.example.rpc.LoginProto.AuthBaseRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthBaseRequest>
        PARSER = new com.google.protobuf.AbstractParser<AuthBaseRequest>() {
      @java.lang.Override
      public AuthBaseRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthBaseRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthBaseRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthBaseRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.rpc.LoginProto.AuthBaseRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AuthBaseResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.entities.AuthBaseResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool error = 1;</code>
     * @return The error.
     */
    boolean getError();

    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>bool success = 3;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code com.example.entities.AuthBaseResponse}
   */
  public static final class AuthBaseResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.entities.AuthBaseResponse)
      AuthBaseResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthBaseResponse.newBuilder() to construct.
    private AuthBaseResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthBaseResponse() {
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AuthBaseResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthBaseResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              error_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 24: {

              success_ = input.readBool();
              break;
            }
            case 32: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.rpc.LoginProto.internal_static_com_example_entities_AuthBaseResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.rpc.LoginProto.internal_static_com_example_entities_AuthBaseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.rpc.LoginProto.AuthBaseResponse.class, com.example.rpc.LoginProto.AuthBaseResponse.Builder.class);
    }

    public static final int ERROR_FIELD_NUMBER = 1;
    private boolean error_;
    /**
     * <code>bool error = 1;</code>
     * @return The error.
     */
    @java.lang.Override
    public boolean getError() {
      return error_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUCCESS_FIELD_NUMBER = 3;
    private boolean success_;
    /**
     * <code>bool success = 3;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (error_ != false) {
        output.writeBool(1, error_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (success_ != false) {
        output.writeBool(3, success_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (error_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, error_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, success_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.rpc.LoginProto.AuthBaseResponse)) {
        return super.equals(obj);
      }
      com.example.rpc.LoginProto.AuthBaseResponse other = (com.example.rpc.LoginProto.AuthBaseResponse) obj;

      if (getError()
          != other.getError()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (getSuccess()
          != other.getSuccess()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getError());
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.rpc.LoginProto.AuthBaseResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rpc.LoginProto.AuthBaseResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rpc.LoginProto.AuthBaseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rpc.LoginProto.AuthBaseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rpc.LoginProto.AuthBaseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rpc.LoginProto.AuthBaseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rpc.LoginProto.AuthBaseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.rpc.LoginProto.AuthBaseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.rpc.LoginProto.AuthBaseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.rpc.LoginProto.AuthBaseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.rpc.LoginProto.AuthBaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.rpc.LoginProto.AuthBaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.rpc.LoginProto.AuthBaseResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.entities.AuthBaseResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.entities.AuthBaseResponse)
        com.example.rpc.LoginProto.AuthBaseResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.rpc.LoginProto.internal_static_com_example_entities_AuthBaseResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.rpc.LoginProto.internal_static_com_example_entities_AuthBaseResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.rpc.LoginProto.AuthBaseResponse.class, com.example.rpc.LoginProto.AuthBaseResponse.Builder.class);
      }

      // Construct using com.example.rpc.LoginProto.AuthBaseResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        error_ = false;

        msg_ = "";

        success_ = false;

        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.rpc.LoginProto.internal_static_com_example_entities_AuthBaseResponse_descriptor;
      }

      @java.lang.Override
      public com.example.rpc.LoginProto.AuthBaseResponse getDefaultInstanceForType() {
        return com.example.rpc.LoginProto.AuthBaseResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.rpc.LoginProto.AuthBaseResponse build() {
        com.example.rpc.LoginProto.AuthBaseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.rpc.LoginProto.AuthBaseResponse buildPartial() {
        com.example.rpc.LoginProto.AuthBaseResponse result = new com.example.rpc.LoginProto.AuthBaseResponse(this);
        result.error_ = error_;
        result.msg_ = msg_;
        result.success_ = success_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.rpc.LoginProto.AuthBaseResponse) {
          return mergeFrom((com.example.rpc.LoginProto.AuthBaseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.rpc.LoginProto.AuthBaseResponse other) {
        if (other == com.example.rpc.LoginProto.AuthBaseResponse.getDefaultInstance()) return this;
        if (other.getError() != false) {
          setError(other.getError());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.rpc.LoginProto.AuthBaseResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.rpc.LoginProto.AuthBaseResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean error_ ;
      /**
       * <code>bool error = 1;</code>
       * @return The error.
       */
      @java.lang.Override
      public boolean getError() {
        return error_;
      }
      /**
       * <code>bool error = 1;</code>
       * @param value The error to set.
       * @return This builder for chaining.
       */
      public Builder setError(boolean value) {
        
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool error = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearError() {
        
        error_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 3;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 3;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 4;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.entities.AuthBaseResponse)
    }

    // @@protoc_insertion_point(class_scope:com.example.entities.AuthBaseResponse)
    private static final com.example.rpc.LoginProto.AuthBaseResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.rpc.LoginProto.AuthBaseResponse();
    }

    public static com.example.rpc.LoginProto.AuthBaseResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthBaseResponse>
        PARSER = new com.google.protobuf.AbstractParser<AuthBaseResponse>() {
      @java.lang.Override
      public AuthBaseResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthBaseResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthBaseResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthBaseResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.rpc.LoginProto.AuthBaseResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_entities_AuthBaseRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_entities_AuthBaseRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_entities_AuthBaseResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_entities_AuthBaseResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017login_rpc.proto\022\024com.example.entities\"" +
      "\230\001\n\017AuthBaseRequest\022\r\n\005refId\030\001 \001(\t\022\023\n\013st" +
      "ringValue\030\002 \001(\t\022\024\n\014stringValues\030\003 \003(\t\022\020\n" +
      "\010intValue\030\004 \001(\005\022\021\n\tlongValue\030\005 \001(\003\022\021\n\tbo" +
      "olValue\030\006 \001(\010\022\023\n\013doubleValue\030\007 \001(\010\"R\n\020Au" +
      "thBaseResponse\022\r\n\005error\030\001 \001(\010\022\013\n\003msg\030\002 \001" +
      "(\t\022\017\n\007success\030\003 \001(\010\022\021\n\ttimestamp\030\004 \001(\0032c" +
      "\n\007AuthRpc\022X\n\005login\022%.com.example.entitie" +
      "s.AuthBaseRequest\032&.com.example.entities" +
      ".AuthBaseResponse\"\000B \n\017com.example.rpcB\n" +
      "LoginProto\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_entities_AuthBaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_entities_AuthBaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_entities_AuthBaseRequest_descriptor,
        new java.lang.String[] { "RefId", "StringValue", "StringValues", "IntValue", "LongValue", "BoolValue", "DoubleValue", });
    internal_static_com_example_entities_AuthBaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_entities_AuthBaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_entities_AuthBaseResponse_descriptor,
        new java.lang.String[] { "Error", "Msg", "Success", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
